100-hours-a-week/17-newsum-fe

- .github/CODEOWNERS
- .github/workflows/pr-restriction.yml
- .gitignore
- package-lock.json
- package.json
- src/pages/HomePage.tsx
Allow pushing to main branch only from the dev branch
> Allow pushing to main branch only from the dev branch

- package-lock.json
- package.json
- src/components/article/ArticleCard.jsx
- src/components/news/NewsBox.jsx
- src/pages/HomePage.jsx
- src/services/articleApi.js
원래 아티클 카드 컴포넌트만 만드려 했는데 테스트 하다보니 메인페이지 카테고리 그리드(NewsBox.jsx)까지 했습니다.
주요 변경사항
1. 초기 아티클 카드에서 요구사항에 맞춰 디자인 수정
2. 아티클 카드 테스트 할 때 필요한 메인페이지 카테고리 그리드 UI 구현
3. 메인페이지 화면 레이아웃 구조 변경 (배너 6개 -> 배너 1개, 오늘의 뉴스 그리드, 최근 본 뉴스 그리드) 
4. 목업 데이터 텍스트 수정 및 이미지 추가(S3 URL로 변경)
이정도가 변경되었습니다!
> design: article-card 컴포넌트 및 NewsBox 컴포넌트 구현(#60)

- src/components/Carousel/Carousel.jsx
- src/pages/HomePage.jsx
메인페이지 캐러셀 구현했습니다.
구현해서 메인페이지에 반영해둔 사진은 다음과 같습니다.
http://newsum-front.s3-website.ap-northeast-2.amazonaws.com
여기에 들어가보시면 변경사항을 확인하실 수 있습니다.
> design: 메인페이지 캐라셀 구현(#59)

- src/components/Layout/BottomNav.jsx
- src/components/category/CategoryGrid.jsx
- src/components/common/CategoryTabs.jsx
- src/components/news/NewsBox.jsx
- src/pages/CategoryPage.jsx
- src/pages/HomePage.jsx
- src/routes/Router.jsx
#65 #70 
> 카테고리 그리드를 만들고, 카테고리 페이지에 적용하였습니다.
> design: 카테고리 그리드 컴포넌트 구현 및 카테고리 페이지 구현

- src/components/Layout/Header.jsx
> fix: 헤더 디자인 수정(#56)

- package-lock.json
- package.json
- src/api/DefaultAxios.jsx
- src/api/TokenAxios.jsx
- src/pages/HomePage.jsx
#88 
> 공통 axios를 만들어 URL과 헤더를 자동 설정되게 하여 API 연동 작업을 수월하게 만들었습니다.
> HomePage.jsx에 사용 예시를 작성해두어 사용하는 방법을 명시하였습니다.
> Feat/88 공통 axios 생성

- public/api/v1/webtoons/main/data.json
- public/api/v1/webtoons/recent/data.json
- public/api/v1/webtoons/top3/data.json
- src/components/Layout/Footer.jsx
- src/pages/HomePage.jsx
- src/services/articleApi.js
#24 #25 #26 #27 
> 메인페이지 UI 구현 완료 및 메인페이지에 포함되는 모든 API 구현 완료
> Design/24 메인 페이지 UI 구현

- src/pages/ArticlePage.jsx
> #28 
> 공유, 좋아요, 북마크 버튼 간격 조정
> design: 공유, 좋아요, 북마크 버튼 간격 조정(#28)

- public/api/v1/webtoons/101/comments/data.json
- src/components/comments/CommentItem.jsx
- src/pages/CommentPage.jsx
> #19 
> api 명세서 기반 api 연동하여 화면에 데이터 표시함
기능 구현이라 이전 화면과 동일함
> feat: 댓글 조회 API 연동(#19)

- index.html
- package-lock.json
- package.json
- src/components/Layout/BottomNav.jsx
- src/components/Layout/Header.jsx
- src/components/tabs/CategoryTabs.jsx
- src/main.jsx
- src/pages/ArticlePage.jsx
- src/pages/CategoryPage.jsx
- src/pages/CommentPage.jsx
> feat: 로그인 없는 api 연동

- src/pages/CategoryPage.jsx
- src/pages/CommentPage.jsx
> feat: 카테고리 페이지 무한스크롤 구현

- .gitignore
- src/components/comments/CommentItem.jsx
- src/components/grid/RecentGrid.jsx
- src/components/tabs/CategoryTabs.jsx
- src/pages/ArticlePage.jsx
- src/pages/CommentPage.jsx
- src/pages/HomePage.jsx
- src/pages/RecentPage.jsx
- src/routes/Router.jsx
#103 
> 댓글 CRUD 연동
> 메인페이지 카테고리별 웹툰 조회 API 연동
> 최근 조회한 웹툰 UI 구현 및 API 연동
> 103 백엔드 api 연결

- src/components/grid/MainGrid.jsx
- src/components/grid/RecentGrid.jsx
- src/routes/Router.jsx
> design: 상세 페이지에서 홈 이동 추가 및 메인페이지 그리드 수정

- src/pages/ArticlePage.jsx
> desgin: 아티클 뉴스 소스 불러오기

- src/components/comments/CommentItem.jsx
- src/components/grid/MainGrid.jsx
- src/pages/ArticlePage.jsx
- src/pages/CommentPage.jsx
> 120 배포 후 qa 진행

- .github/workflows/frontend.yml
클라우드 레포 #91
> 프론트엔드 CI/CD 파이프라인을 구성했습니다.
>
> ci : 프론트엔드 CI/CD 파이프라인 구성(#91)

- .github/workflows/frontend.yml
> 91 프론트 cicd 파이프라인구축

- .github/workflows/frontend.yml
> ci : 파이프라인 수정

- .github/workflows/frontend.yml
> ci : update

- .github/workflows/fe-dev-ci-test.yml
> #112 
> frontend.yml 수정
> fe-dev-ci-test.yml 생성
>
> ci와 cd 파일을 분리하고자 했습니다.
> fe-dev-ci-test upload & frontend.yml update

- src/components/Layout/BottomNav.jsx
- src/components/search/SearchBar.jsx
- src/components/search/SearchResultItem.jsx
- src/hooks/useDebounce.js
- src/pages/SearchPage.jsx
- src/routes/Router.jsx
> Feat(#140, #142) : 검색 기능 UI 구현 및 API연동

- src/components/Layout/BottomNav.jsx
- src/pages/BookmarkPage.jsx
- src/routes/Router.jsx
#154 #145 
북마크 페이지 구현하였습니다.
로그인한 유저의 아이디로 북마크 테이블을 조회하여 북마크항목들을 보여줍니다.
드롭박스 추가는 #135  에서 구현하여 적용할 예정입니다.
비로그인 유저가 접근할려고 할 시,
>> 배경에 북마크 페이지로 넘어가지 않고, 머물러있는 페이지에서 머물도록 수정할 예정입니다.
코드에서 이상한 부분 있으면 말씀해주세요 감사합니다
컴포넌트 빼먹은 부분있으면 말씀 부탁드립니다.
감사합니다.
> feat: 사용자 북마크 페이지 프론트 와 api연동, 페이지 구현 완료

- .github/workflows/frontend.yml
> frontedn.yml update

- .github/workflows/frontend.yml
Swagger 설정은 미완입니다.
#110 (클라우드)
> 카카오 로그인 문제 해결 및 Swagger 프록시 설정
이렇게 나와서 추가 수정이 필요할 듯 합니다.
>
> ci : 카카오 로그인 해결 및 Swagger 설정 추가

- .github/workflows/fe-dev-cd.yml
> 110 로그인 안되는 이슈 해결

- .github/workflows/fe-dev-cd.yml
- .github/workflows/fe-dev-ci.yml
- .github/workflows/fe-main-cd.yml
- .github/workflows/fe-main-ci.yml
클라우드 #114
> Main 파이프라인을 간단한 스모크 테스트를 추가하여 구현하였습니다.
> Dev 파이프라인에 하드코딩 되어 있던 URL을 수정하였습니다.
>
> 114 main cicd 파이프라인 구축

- .github/workflows/pr-restriction.yml
- .github/workflows/reviewers.yml
> 클라우드 #115
> 리뷰어 할당 yml 파일 설정
>
> ci : 리뷰어 설정

- src/components/comments/CommentItem.jsx
- src/components/dropdown/CategoryDropdown.jsx
- src/pages/BookmarkPage.jsx
- src/routes/Router.jsx
#135 
북마크 즐겨찾기, aI 작가 즐겨찾기, 키워드 즐겨찾기 페이지 이동을 위한 드롭박스 메뉴를 구현했습니다.
오버레이부분 후에 수정이 필요합니다.
> [#135] 북마크 페이지 드롭다운메뉴 추가 

- .github/workflows/fe-release.yml
> [이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)](https://github.com/100-hours-a-week/17-newsum-cl/issues/119)
>
> fe-release.yml test

- src/components/bookmark/BookmarkMenu.jsx
- src/components/dropdown/CategoryDropdown.jsx
- src/pages/BookmarkPage.jsx
> #135 
> 드롭 다운 메뉴 디자인 수정 했습니다.
>
> fix : 드롭다운 메뉴 디자인 수정(#135)

- .github/workflows/fe-dev-ci-test.yml
테스트 통과하기 위해 Path fe-dev-ci-test* 로 수정
>
> ci : infsical test 후 복구

- src/App.jsx
> test: display VITE_RELEASE_TEST_TOKEN in App

- package-lock.json
- src/pages/KeywordAddPage.jsx
#184  [#187](https://github.com/100-hours-a-week/17-newsum-fe/issues/187)
사용자의 키워드 삭제 및 키워드 리스트를 가져옵니다
-
감사합니다
> [#184] 키워드 북마크 페이지 키워드 삭제 api, 리스트 api 서버 연동 

- .github/workflows/fe-prod-s3-cd.yml
aws s3에 업로드할때 env를 사용해서 빌드하도록 수정
infisical env를 받아오도록 수정
> infisical .env 수정

- src/pages/HomePage.jsx
- src/pages/TodayWebtoonsPage.jsx
- src/routes/Router.jsx
#207 
오늘의 웹툰 더보기 클릭시
오늘 생성된 웹툰들을 전부 보여줍니다
>
> feat: 오늘의 웹툰 더보기 api 연동

- src/utils/sseConnect.jsx
> chore : 동시시청자수 API 경로 수정
